name: Trigger auto deployment for testframeworkchaos

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/testframeworkchaos-AutoDeployTrigger-1600172f-a8d5-40fb-83d4-99c7e46866fe.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TESTFRAMEWORKCHAOS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TESTFRAMEWORKCHAOS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TESTFRAMEWORKCHAOS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.TESTFRAMEWORKCHAOS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTFRAMEWORKCHAOS_REGISTRY_PASSWORD }}
          containerAppName: testframeworkchaos
          resourceGroup: Framework
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


